### ISSUE TITLE
stats: prepare counters for main page

### ISSUE THREAD

**Issue by sevenzing** [blockscout/blockscout-rs#1080]
need to show info from `stats` 
 
* on homepage:
![Image](https://github.com/user-attachments/assets/2aedc7da-ebc1-4aba-8209-7bfc2c6d4cc9)
 
* on /transactions page
![Image](https://github.com/user-attachments/assets/f5fa0ca2-f92d-4fd3-ac84-6045a5ca9e37)
* on /verified-contracts page
![Image](https://github.com/user-attachments/assets/e3265c5a-d080-4a43-915d-2a4c66ef8c47)

for now this UI takes this information from elixir backend. 

main page:
- [x] fix `Average block time` counter. for now it calculates average amount across **all blocks**. blockscout implements custom logic here: https://github.com/blockscout/blockscout/blob/e16236243195deb06d6d4b9e0bb67c534b2f04ad/apps/explorer/lib/explorer/counters/average_block_time.ex#L75-L81
need to write the same thing. (#1117)
- [x] total blocks - to update almost in real time (as currently in blockscout) (#1137)
- [x] total transactions - to update almost in real time (as currently in blockscout) (#1144)
- [x] total addresses - to update almost in real time (as currently in blockscout)
- [x] number of transactions for prev day (#1120)
- [x] daily transactions for 30 days chart (#1147)

transactions page:
- [x] transactions for 24h
- [x] pending transactions
- [x] transaction fees for 24h
- [x] avg transaction fee 24h

verified contracts page:
- [x] more frequent total contracts update
- [x] new contracts for 24h
- [x] more frequent total verified contracts update
- [x] new verified contract for 24h

**important:** `stats` should calculate counters even if blockscout dint finish indexing yet

**Comment by bragov4ik** [comment]
note: added daily txns chart (pic). we figured out how to add it while letting it update immediately (w/o waiting for indexing)

![image](https://github.com/user-attachments/assets/a3a5fd20-924a-4056-aee8-9a6f99cd86d6)

**Comment by bragov4ik** [comment]
![image](https://github.com/user-attachments/assets/80431c44-2447-41d4-a92e-43ccfc08679a)
on staging

**Comment by bragov4ik** [comment]
everything is merged in main
