### ISSUE TITLE
Ethereum Bytecode Database

### ISSUE THREAD

**Issue by rimrakhimov** [blockscout/blockscout-rs#200]
Our initial goal was to have a database that would share all verified contracts info between all supported chains. Currently each chain that supports Blockscout has its own version of the database for verified smart-contracts. The independence of databases prevents us from sharing verified contracts and their method identifiers between chains. E.g., If the contract were verified on Ethereum Mainnet, it wouldn’t be possible to get it from Gnosis Chain, even if it would have the same creation transaction input.

The main idea behind Ethereum Bytecode Database is to change mapping from `chain -> contract address -> sources`, into `bytecode -> sources`. That is, the service maps source codes directly to bytecodes. In that case, we would not care about the chains and actual contracts but only about bytecode-sourceCode correspondence. Idea is similar to what [4bytes](https://www.4byte.directory/) or [sigEth](https://sig.eth.samczsun.com/) do. But instead of looking for the function signature based on its identifier, we would look for the contracts' source codes based on their bytecodes.

Full description: https://www.notion.so/blockscout/Ethereum-Bytecode-Database-617d17128797414fb07308a4c59bac45

User Stories: 

- [x] 1. [Tech story] Create a basic service template that provides an API and initializes a database
https://github.com/blockscout/blockscout-rs/issues/201
- [x] 2. Update smart-contract-verifier service
https://github.com/blockscout/blockscout-rs/issues/174
- [x] 3. Implement verification of smart-contracts
https://github.com/blockscout/blockscout-rs/issues/208
- [x] 4. Implement search for the source codes via bytecode
https://github.com/blockscout/blockscout-rs/issues/209
- [ ] 5. Create extractors of verified contracts
https://github.com/blockscout/blockscout-rs/issues/213
